name: chambita
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  curved_navigation_bar: ^0.3.4
  http: any
  shared_preferences: any
  cupertino_icons: ^0.1.3
  bubble_tab_indicator: ^0.1.4
  fl_chart: ^0.9.4
  flutter_datetime_picker: ^1.3.8
  fluttertoast: ^4.0.0
  flare_flutter: any
  sqflite: ^1.3.0
  path_provider: ^1.6.11
  path: ^1.7.0
  random_color: ^1.0.5
  google_sign_in: ^4.5.5
  flutter_facebook_login: ^3.0.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1+1

  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  animated_theme_switcher: ^1.0.5 

  flutter_staggered_grid_view: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/logos/facebook.jpg
    - assets/logos/google.jpg
    - assets/logos/logo_chambita__.png
    - assets/logos/frans.jpg


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
        
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
